#!/bin/bash
# Syntax: raw2rinex input output [teqcoptions]
# Description: GNSS raw data files convertion to daily RINEX 2.11
# Arguments:
#	      input	Directory or filename of raw data (Leica, Trimble, Rinex)
#              compressed of not
#	     output Either output directory to write rinex (must exist), or any
#              output rinex filename
#	teqcoptions	Any options to add to teqc (example: -O.dec 30 -O.rt "receiver"
#              -O.at "antenna")
#
# Dependencies:
#            teqc for all data preprocessing, binary available at unavco
#                 https://www.unavco.org/software/data-processing/teqc/teqc.html
#          gunzip with .gz files
#           unzip with .zip files
#         CRX2RNX with Hatanaka files
#    	 runpkr00 with some Trimble .T02 files (MUST be version ≥ 6.03)
# cnvrnx3-rnx2-v3 with Rinex v.3 files, source available at
#                 http://acc.igs.org/misc/cnvrnx3-rnx2-v3.f
#
#
# Author: F. Beauducel / DOMERAPI <beauducel@ipgp.fr>
# Created: 2014-01-12
# Updated: 2023-08-21
#
# **** Updates
# ** 2026-04-23 Pierre Sakic
# - Add the option to use ConvertoCPP instead of teqc for RINEX3 files
# ** 2023-08-07 Pierre Sakic 
# - Handle the RINEX3 as it is
#   (no downgrade to RNX2, but no modification of the header either)
# ** 2024-05-05 Pierre Sakic
# - Handle gzip compression for RINEX2 
#   (NB: RINEX3 are always gzipped by design)

### comment the variable VERBOSE to disable the verbose mode 
# (do not switch to 0, the test is based on variable initialization...)
# VERBOSE=1

# Check if ConvertoCPP is available and set the flag accordingly
if command -v ConvertoCPP &> /dev/null; then
	if [ ! -z $VERBOSE ]; then
		echo "INFO: ConvertoCPP found, RINEX3 files can be spliced"
	fi
	USE_CONVERTO=1
else
	if [ ! -z $VERBOSE ]; then
		echo "WARN: ConvertoCPP not found, RINEX3 files can't be spliced"
	fi
	USE_CONVERTO=0
fi

if [ $# -lt 2 ]; then
	echo "raw2rinex input output [teqc options]"
	echo 'NB1: multiple inputs: "input1 input2 ... inputN" (between double quotes)'
	exit 0;
fi

### ------- temporary directory 
# the main tmp dir can be customized,
# working in the default /tmp can be tricky especially for big repro
if [ -z $TMPDIRMAIN ] || [ ! -d  $TMPDIRMAIN ]; then
        if [ ! -d  $TMPDIRMAIN ]; then
		echo "WARN: given main temp dir $TMPDIRMAIN does not exists, defaut /tmp will be used"
	fi
        TMPDIRMAIN="/tmp/"
fi

tmpdir=$(mktemp -d $TMPDIRMAIN/raw2rinex.XXXXXXXXXX)
cd $tmpdir

rawdir=$1
if [ -d "$rawdir" ]; then
	files=$(find $rawdir -type f)
else
	files=$(ls $rawdir 2>/dev/null)
fi

#echo "** files = $files"

outdir=$2

if [ "$#" -ge 3 ]
then
	shift
	shift
	teqcopt=$@
fi

# --- copy and uncompress files in a temporary directory
for f in $files
do
	# unzip (-o option is mandatory to avoid prompting in some circumstances !)
	if [[ $f == *".zip" ]]; then
		unzip -oq $f -d $tmpdir
	else
		cp -L $f $tmpdir/
	fi

	# gunzip (must copy first before unzip)
	if [[ $f == *".gz" ]]; then
		gunzip -f $tmpdir/*.gz
	fi
done

# -------------- SELECT FILES --------------------------------------------------------
# ------ RINEX2 ------
# --- try RINEX2 uncompressed files
rf=$(find $tmpdir -iname "*.??o" | sort )
if [ ! -z "$rf" ]; then
	echo "   Found some RINEX2 files in $rawdir: proceeding..."
	# If file has short name but is a RINEX3 inside, we downgrade it to RINEX2
	for f in $rf; do
		if [[ $(head -n1 $f | awk '{print $1}') == '3.01' ]]; then
			cnvrnx3-rnx2-v3 $f +0 g
			if [ -s $f.gps.rnx2 ]; then
				# must remove these specific header lines for teqc...
				grep -v "PHASE SHIFTS" $f.gps.rnx2 > $f
			fi
		fi
	done
	rawfiles=$rf
	obsfiles=$(find $tmpdir -iname "*.??o" | sort )
	navfiles=$(find $tmpdir -iname "*.??n" | sort )
	teqcfmt=""
    skipteqc=0
	skipconverto=1
fi

# --- try RINEX2 Hatanaka files
rf=$(find $tmpdir -name "*.??d.Z" -o -name "*.??d.gz" -o -name "*.??d" | sort )
if [ ! -z "$rf" ]; then
	echo "   Found some RINEX2 Hatanaka files in $rawdir: proceeding..."
	# must convert ??d to ??o
	for f in $rf; do
		if [[ $f == *".Z" ]] || [[ $f == *".gz" ]]; then
			gunzip -f $f
			f=${f%.*}
		fi
		CRX2RNX $f -f
	done
	rawfiles=$(find $tmpdir -iname "*.??o" | sort )
	obsfiles=$rawfiles
	navfiles=""
	teqcfmt=""
    skipteqc=0
	skipconverto=1
fi

# ------ RINEX3 ------
# --- try RINEX3 uncompressed files
rf=$(find $tmpdir -iname "*.rnx" | sort )
if [ ! -z "$rf" ]; then
	echo "   Found some RINEX3 files in $rawdir: proceeding..."
	rawfiles=$rf
	obsfiles=$rf
	#navfiles=$(find $tmpdir -iname "*.??n" | sort )
	teqcfmt=""
    skipteqc=1
	skipconverto=0
fi

# --- try RINEX3 Hatanaka files
rf=$(find $tmpdir -name "*.crx.gz" -o -name "*.crx" | sort )
if [ ! -z "$rf" ]; then
	echo "   Found some RINEX3 Hatanaka files in $rawdir: proceeding..."
	# must convert ??d to ??o
	for f in $rf; do
		if [[ $f == *".gz" ]]; then
			gunzip -f $f
			f=${f%.*}
		fi
                f2=${f%.*}'.rnx'
                cat $f | CRX2RNX > $f2
	done
	rawfiles=$(find $tmpdir -iname "*.crx" | sort )
	obsfiles=$(find $tmpdir -iname "*.rnx" | sort )
	navfiles=""
	teqcfmt=""
    skipteqc=1
	skipconverto=0
fi

# ------ RAW Manufacturer files ------
# --- try Leica mdb...
rf=$(find $tmpdir -name "*.m??" | sort )
if [ ! -z "$rf" ]; then
	echo "   Found some Leica files in $rawdir: proceeding..."
	rawfiles=$rf
	obsfiles=$(find $tmpdir -iname "*.m??" | sort )
	navfiles=$rawfiles
	teqcfmt="-lei mdb"
    skipteqc=0
	skipconverto=1
fi

# --- try Trimble T02...
rf=$(find $tmpdir -name "*.T02" | sort )
if [ ! -z "$rf" ]; then
	echo "   Found some Trimble files in $rawdir: proceeding..."
	# must convert T02 to tgd (dat without -g option)
	for f in $rf; do
		runpkr00 -g -d $f
	done
	rawfiles=$(find $tmpdir -iname "*.tgd" | sort )
	obsfiles=$rawfiles
	navfiles=$rawfiles
	teqcfmt="-tr d"
    skipteqc=0
	skipconverto=1
fi

if [ -z "$rawfiles" ]; then
	echo "No valid GNSS file found in $rawdir... abort."
	exit
fi

tmprnx=$tmpdir/rinex
tmpnav=$tmpdir/nav

# -------------- Apply teqc or Converto --------------------------------------------------------
# Perform an (actual) Raw-To-RINEX(2) conversion If Necessary (with teqc)
# Or Splice RINEX2 Files To A Single RINEX2 File (with teqc)
# Or Splice RINEX3 Files To A Single RINEX3 File (with Converto)
# Or take the 1st RINEX3 (Skip Teqc & Converto

if [ $skipteqc -eq 0 ]; then
        if [ ! -z $VERBOSE ]; then
                echo "teqc $teqcfmt $teqcopt $obsfiles > $tmprnx"
        fi
        teqc $teqcfmt $teqcopt $obsfiles > $tmprnx
elif [[ $USE_CONVERTO -eq 1 && $skipconverto -eq 0 ]]; then
        if [ ! -z $VERBOSE ]; then
                echo "ConvertoCPP $teqcopt -cat -i $obsfiles -o $tmprnx"
        fi
		ConvertoCPP $teqcopt -cat -i $obsfiles -o $tmprnx
else    
        obsfiles_1st=`echo $obsfiles | head -1 | awk '{print $1}'`
        if [ ! -z $VERBOSE ]; then
                echo "   RNX3: no teqc possible & no Converto avaiable."
				echo "     > splicing/modding skipped, assuming header's ant/rec are correct!"
				echo "     > 1st file only is kept: $obsfiles_1st"
				echo "   cp -f $obsfiles $tmprnx"		
        fi
        cp $obsfiles_1st $tmprnx
fi

# -------------- output RINEX files --------------------------------------------------------
# case A: output **directory** specified 
#         => archiving RINEX with proper 8.3 short names (obs and nav)
if [ -d $outdir ]; then
	if [ ! -z $VERBOSE ]; then
		echo "  case A: output **directory** specified"
	fi
	# gets the station code from the filename
	for f in $rawfiles; do
		#echo $f
		filebn=$(basename $f)
		code=${filebn:0:4}
		rinex=$outdir/${filebn:0:8}
	done
	code=$(echo $code | tr '[:lower:]' '[:upper:]')
	starttime=$(teqc +meta $tmprnx | grep "start date" | sed -e 's/.*: //' | sed -e 's/[ \t]*//')
	yy=${starttime:2:2}
	echo "   cp -f $tmprnx ${rinex}.${yy}o"
	cp -f $tmprnx ${rinex}.${yy}o
	if [ ! -z "$navfiles" ]; then
		teqc ${teqcfmt}n $teqcopt $navfiles > $tmpnav
		if [ ! -z $VERBOSE ]; then
			echo "   cp -f $tmpnav ${rinex}.${yy}n"
		fi
		cp -f $tmpnav ${rinex}.${yy}n
	fi

# case B: output **file** specified 
#         => write the RINEX using given filename
# most usual mode, used by gnss_run_gipsyx
else
	if [ ! -z $VERBOSE ]; then
		echo "  case B: output **file** specified"
		echo "   cp -f $tmprnx $outdir"
	fi
	cp -f $tmprnx $outdir
fi

if [ -z $VERBOSE ]; then
	rm -rf $tmpdir
fi
